### ISSUE TITLE
mkrootfs: create fixed size partition instead of 

### ISSUE THREAD

**Issue by gianlzed** [zededa/zenbuild#22]

**Comment by gianlzed** [comment]
mkrootfs right now creates IMGA and IMGB partition based on the size of the first rootfs. We need to decide a max size, and stick to it.

Current rootfs is ~150Mb (thanks to squashfs). Uncompressed rootfs is ~500Mb in the case of Ext4. We should pick something between the two values.

Step 1: pick a aribtrary size
Step 2: set it, and make mkrootfs's size configurable.

**Comment by rvs** [comment]
I'd go with 300Mb for now

**Comment by gianlzed** [comment]
@rvs, config_part merge chooses 300MB as the IMGA and IMGB size.

All you need to change it in the future, hence to make it configurable, is change IMAGE_SIZE in pkg/mkrootfs/make-root.

Closing it.
