### ISSUE TITLE
Rename fallback.img, remove supermicro.* targets

### ISSUE THREAD

**Issue by gianlzed** [zededa/zenbuild#25]
the name fallback.img doesn't make any sense, it was originally meant to point out at having the fallback bootlader in it.

Also this raises the question whether we should remove the old supermicro (img,iso) targets.

We should pick a name for fallback.img that is liked by everyone.

**Comment by eriknordmark** [comment]
I think having a factory.img (or installer.img or usb.img) which has /config, IMGA and IMGB makes sense. That's just a rename.
We can drop the old supermicro.img.

We'll keep the rootfs.img to build updates. It would be nice if make rootfs.img could do that (I think I saw some failure when I tried - so instead I make fallback.img and use the resulting rootfs.img)

**Comment by gianlzed** [comment]
What kind of error you see when you do that? that was probably due to size mismatch, which has been fixed recently. Otherwise, should be fixed. rootfs.img is meant exactly for that.

**Comment by eriknordmark** [comment]
Starts with warnings
nordmark@bobo:~/zenbuild$ ZTOOLS_TAG=simplify make rootfs.img 
make -C pkg
make[1]: Entering directory '/home/nordmark/zenbuild/pkg'
(cd ..; ./parse-pkgs.sh pkg/kmod_pfring/Dockerfile.in > pkg/kmod_pfring/Dockerfile)
open /home/nordmark/zenbuild/pkg/test-cert/build.yml: no such file or directory
(cd ..; ./parse-pkgs.sh pkg/qrexec-lib/Dockerfile.in > pkg/qrexec-lib/Dockerfile)
open /home/nordmark/zenbuild/pkg/test-cert/build.yml: no such file or directory
(cd ..; ./parse-pkgs.sh pkg/qrexec-dom0/Dockerfile.in > pkg/qrexec-dom0/Dockerfile)
open /home/nordmark/zenbuild/pkg/test-cert/build.yml: no such file or directory
(cd ..; ./parse-pkgs.sh pkg/zedctr/Dockerfile.in > pkg/zedctr/Dockerfile)
open /home/nordmark/zenbuild/pkg/test-cert/build.yml: no such file or directory
(cd ..; ./parse-pkgs.sh pkg/test-conf/Dockerfile.in > pkg/test-conf/Dockerfile)
open /home/nordmark/zenbuild/pkg/test-cert/build.yml: no such file or directory
(cd ..; ./parse-pkgs.sh pkg/mkflash//Dockerfile.in > pkg/mkflash//Dockerfile)
open /home/nordmark/zenbuild/pkg/test-cert/build.yml: no such file or directory
Building "zededa/grub:1b11f71c1babebdf634381dc256c7b4ca2f49a5e"
1b11f71c1babebdf634381dc256c7b4ca2f49a5e: Pulling from zededa/grub


Then gets failures like
tools/kconfig/conf.c: In function 'check_stdin':
tools/kconfig/conf.c:77:3: warning: format not a string literal and no format arguments [-Wformat-security]
   printf(_("aborted!\n\n"));
   ^~~~~~
tools/kconfig/conf.c:78:3: warning: format not a string literal and no format arguments [-Wformat-security]
   printf(_("Console input/output is redirected. "));
   ^~~~~~
tools/kconfig/conf.c:79:3: warning: format not a string literal and no format arguments [-Wformat-security]
   printf(_("Run 'make oldconfig' to update configuration.\n\n"));
   ^~~~~~
tools/kconfig/conf.c: In function 'conf_askvalue':
tools/kconfig/conf.c:89:3: warning: format not a string literal and no format arguments [-Wformat-security]
   printf(_("(NEW) "));
   ^~~~~~
tools/kconfig/conf.c: In function 'conf_choice':
tools/kconfig/conf.c:290:5: warning: format not a string literal and no format arguments [-Wformat-security]
     printf(_(" (NEW)"));
     ^~~~~~
tools/kconfig/conf.c: In function 'check_conf':
tools/kconfig/conf.c:438:6: warning: format not a string literal and no format arguments [-Wformat-security]
      printf(_("*\n* Restart config...\n*\n"));
      ^~~~~~
tools/kconfig/conf.c: In function 'main':
tools/kconfig/conf.c:640:6: warning: format not a string literal and no format arguments [-Wformat-security]
      _("\n*** The configuration requires explicit update.\n\n"));
      ^
tools/kconfig/conf.c:693:4: warning: format not a string literal and no format arguments [-Wformat-security]
    fprintf(stderr, _("\n*** Error during writing of the configuration.\n\n"));
    ^~~~~~~
tools/kconfig/conf.c:697:4: warning: format not a string literal and no format arguments [-Wformat-security]
    fprintf(stderr, _("\n*** Error during update of the configuration.\n\n"));
    ^~~~~~~
tools/kconfig/conf.c:708:4: warning: format not a string literal and no format arguments [-Wformat-security]
    fprintf(stderr, _("\n*** Error during writing of the configuration.\n\n"));
    ^~~~~~~


Odd thing it is rebuilding the kernel even though I just built fallback.img.

So it is doing something very different

**Comment by rvs** [comment]
Guys, I've removed the supermicro targets. Not closing this, since you also wanted to rename fallback.img but perhaps we can just live with it for now -- up to you.

**Comment by gianlzed** [comment]
Thanks Roman, This was the plan all along. I have no opinion on the name,
as stated in the past multiple times.

G.

On Thu, Mar 1, 2018 at 6:06 PM, Roman V Shaposhnik <notifications@github.com
