### ISSUE TITLE
Create prototype yml generator.

### ISSUE THREAD

**Issue by glguida** [zededa/zenbuild#3]
The template parser, aka the poor man's yml generator,  is hackish and getting hackier. It is composed of a quickly written set of shell scripts.

This was good for a quick demonstration of what zenbuild should be and to get something off the ground quickly, but it should really become a much better tool. Specifically, the following problems are found:

1. It is impossible to add board-specific features/packages to a board yml (images/*.yml) without having to copy the whole template into a new one. E.g., if I want to change the command line for a specific board I *have* to create a new file.
2. Support for adding optional packages (e.g., ztools) is an afterthought. Should be a first class citizen in this system.

This issue is about creating a prototype that will overcome the above limitation.

**Comment by rvs** [comment]
Closing this since the discussion seems to have moved to #87
