### ISSUE TITLE
Create an ARM port targeting HiKey 

### ISSUE THREAD

**Issue by rvs** [zededa/zenbuild#4]
We need to be able to produce images that can boot on HiKey (https://www.96boards.org/product/hikey/) the same way that we're now booting on Supermicro.

This shouldn't be terribly complicated since linuxkit itself is supporting ARM pretty nicely these days  and also because HiKey is also UEFI enabled (just like supermicro).

Cross-compiling is out of scope for now.

**Comment by cherry-zededa-com** [comment]
I'll get this - @rvs - not sure how to make the "assignment"

**Comment by rvs** [comment]
There should be an "Assignees" on the right on your screen. I've just assigned it to you, but also curious if you can do it yourself.

**Comment by cherry-zededa-com** [comment]
Wasn't able to myself - the button was greyed out.

**Comment by rvs** [comment]
I think I've just fixed it -- can you try again and see if the button is
now active?

Thanks,
Roman.

On Thu, Nov 16, 2017 at 9:36 AM, cherry-zededa-com <notifications@github.com
> wrote:

> Wasn't able to myself - the button was greyed out.
>
> On Thu, Nov 16, 2017 at 4:47 PM, Roman V Shaposhnik <

**Comment by cherry-zededa-com** [comment]
Taking discussion off web issue tracker:

**Comment by rvs** [comment]
Closing the issue since we have a fully functioning port now. There are a few potential rough edges still, but it seems to boot and run.
